version: 2
jobs:
  build:
    working_directory: ~/foodguy
    docker:
      - image: trenpixster/elixir:1.3.2
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: ubuntu
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_TEST_REPORTS/exunit
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
